<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use RuntimeException;

final class SportsRulesService {
 public function __construct(private PDO $db){}
 public function applyWalkover(int $matchId,int $winnerTeamId,string $reason,?int $userId):void{$m=$this->match($matchId);if(!in_array($winnerTeamId,[(int)$m['home_team_id'],(int)$m['away_team_id']],true))throw new RuntimeException('Vencedor invalido para W.O.');$r=(new RuleConfigurationService($this->db))->active((int)$m['tournament_id']);[$w,$l]=array_map('intval',explode('-',str_replace(' ','',(string)($r['points']['walkover_score']??'3-0'))));$home=$winnerTeamId===(int)$m['home_team_id']?$w:$l;$away=$winnerTeamId===(int)$m['away_team_id']?$w:$l;$this->db->prepare('UPDATE matches SET home_score=?,away_score=?,status="walkover",updated_at=NOW() WHERE id=?')->execute([$home,$away,$matchId]);$this->db->prepare('INSERT INTO match_reports(match_id,state,organizer_notes,created_at,updated_at) VALUES(?,"administrative",?,NOW(),NOW()) ON DUPLICATE KEY UPDATE organizer_notes=VALUES(organizer_notes),updated_at=NOW()')->execute([$matchId,$reason]);AuditService::record('walkover','matches',$matchId,['status'=>$m['status']],['winner_team_id'=>$winnerTeamId,'score'=>$home.'-'.$away,'reason'=>$reason]);(new StandingsService($this->db))->recalculate((int)$m['tournament_id']);}
 public function applyPenalty(int $tid,int $team,int $delta,string $type,string $reason,?int $user):int{$s=$this->db->prepare('INSERT INTO team_penalties(tournament_id,team_id,points_delta,penalty_type,reason,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,"active", ?,NOW(),NOW())');$s->execute([$tid,$team,$delta,$type,$reason,$user]);$id=(int)$this->db->lastInsertId();(new StandingsService($this->db))->recalculate($tid);AuditService::record('apply_penalty','team_penalties',$id,[],['team_id'=>$team,'points_delta'=>$delta,'type'=>$type]);return$id;}
 public function revokePenalty(int $id,string $reason,?int $user):void{$s=$this->db->prepare('SELECT * FROM team_penalties WHERE id=? AND status="active" AND deleted_at IS NULL');$s->execute([$id]);$p=$s->fetch()?:throw new RuntimeException('Punicao invalida.');$this->db->prepare('UPDATE team_penalties SET status="revoked",revoked_at=NOW(),revoked_by=?,appeal_note=?,updated_at=NOW() WHERE id=?')->execute([$user,$reason,$id]);(new StandingsService($this->db))->recalculate((int)$p['tournament_id']);AuditService::record('revoke_penalty','team_penalties',$id,$p,['reason'=>$reason]);}
 public function recordCard(int $matchId,int $teamId,?int $personId,string $type,?int $user):int{$event=(new MatchReportService($this->db))->addEvent($matchId,['team_id'=>$teamId,'person_id'=>$personId,'event_type'=>$type,'period'=>'first'],$user);$m=$this->match($matchId);$units=$type==='yellow'?1:0;$this->db->prepare('INSERT INTO discipline_ledger(tournament_id,person_id,team_id,match_id,event_id,card_type,card_units,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())')->execute([$m['tournament_id'],$personId,$teamId,$matchId,$event,$type,$units]);$this->refreshSuspensions((int)$m['tournament_id']);return$event;}
 public function refreshSuspensions(int $tid):void{$rules=(new RuleConfigurationService($this->db))->active($tid);$limit=(int)($rules['discipline']['yellow_limit']??3);$red=(int)($rules['discipline']['red_suspension']??1);$q=$this->db->prepare('SELECT person_id,SUM(card_units) yellows,MAX(card_type IN ("red","second_yellow")) sent FROM discipline_ledger WHERE tournament_id=? AND status="active" AND deleted_at IS NULL AND person_id IS NOT NULL GROUP BY person_id');$q->execute([$tid]);foreach($q as $row){$needed=(int)$row['sent']?$red:((int)$row['yellows']>=$limit?1:0);if(!$needed)continue;$exists=$this->db->prepare('SELECT id FROM suspensions WHERE tournament_id=? AND person_id=? AND status="active" AND deleted_at IS NULL LIMIT 1');$exists->execute([$tid,$row['person_id']]);if(!$exists->fetchColumn())$this->db->prepare('INSERT INTO suspensions(tournament_id,person_id,reason,matches_total,matches_served,status,created_at,updated_at) VALUES(?,?,?, ?,0,"active",NOW(),NOW())')->execute([$tid,$row['person_id'],(int)$row['sent']?'Automatic red card':'Automatic yellow cards',$needed]);}}
 public function serveSuspensions(int $matchId):void{$m=$this->match($matchId);$q=$this->db->prepare('SELECT s.id FROM suspensions s JOIN registrations r ON r.person_id=s.person_id AND r.tournament_id=s.tournament_id WHERE s.tournament_id=? AND s.status="active" AND s.matches_served<s.matches_total AND s.deleted_at IS NULL AND r.team_id IN (?,?)');$q->execute([$m['tournament_id'],$m['home_team_id'],$m['away_team_id']]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id){$this->db->prepare('INSERT IGNORE INTO suspension_fulfillments(suspension_id,match_id,served_at,created_at) VALUES(?,?,NOW(),NOW())')->execute([$id,$matchId]);$this->db->prepare('UPDATE suspensions SET matches_served=(SELECT COUNT(*) FROM suspension_fulfillments WHERE suspension_id=?),status=IF(matches_served+1>=matches_total,"served","active"),updated_at=NOW() WHERE id=?')->execute([$id,$id]);}}
 public function assertLineupAllowed(int $matchId,int $teamId,array $people,bool $exception=false,string $reason=''):void{foreach($people as $id){$s=$this->db->prepare('SELECT COUNT(*) FROM suspensions WHERE tournament_id=(SELECT tournament_id FROM matches WHERE id=?) AND person_id=? AND status="active" AND matches_served<matches_total AND deleted_at IS NULL');$s->execute([$matchId,$id]);if($s->fetchColumn()&&!$exception)throw new RuntimeException('Atleta suspenso.');if($s->fetchColumn()&&$exception&&trim($reason)==='')throw new RuntimeException('Justificativa obrigatoria para excecao.');}}
 private function match(int $id):array{$s=$this->db->prepare('SELECT * FROM matches WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);return$s->fetch()?:throw new RuntimeException('Partida nao encontrada.');}
}
