<?php
declare(strict_types=1);
namespace App\Services;
use PDO;
final class StandingsService {
 public function __construct(private PDO $db){}
 public function recalculate(int $tid,?int $groupId=null):array{$groups=$groupId?[['id'=>$groupId]]:$this->groups($tid);$out=[];foreach($groups as $g){$rows=$this->calculateGroup($tid,(int)$g['id']);$this->db->prepare('DELETE FROM standings_snapshots WHERE tournament_id=? AND group_id=?')->execute([$tid,$g['id']]);$i=$this->db->prepare('INSERT INTO standings_snapshots(tournament_id,stage_id,group_id,team_id,played,wins,draws,losses,goals_for,goals_against,points,position,calculated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW())');foreach($rows as $n=>$r){$r['position']=$n+1;$i->execute([$tid,$r['stage_id'],$g['id'],$r['team_id'],$r['played'],$r['wins'],$r['draws'],$r['losses'],$r['goals_for'],$r['goals_against'],$r['points'],$r['position']]);$out[]=$r;}}return$out;}
 public function forGroup(int $tid,int $gid):array{$s=$this->db->prepare('SELECT s.*,t.name team_name FROM standings_snapshots s JOIN teams t ON t.id=s.team_id WHERE s.tournament_id=? AND s.group_id=? ORDER BY s.position');$s->execute([$tid,$gid]);return$s->fetchAll();}
 public function forPublic(int $id):array{$s=$this->db->prepare('SELECT s.*,t.name team_name FROM standings_snapshots s JOIN teams t ON t.id=s.team_id WHERE s.tournament_id=? ORDER BY COALESCE(s.group_id,0),s.position');$s->execute([$id]);return$s->fetchAll();}
 private function calculateGroup(int $tid,int $gid):array{$s=$this->db->prepare('SELECT g.stage_id,a.team_id,t.name FROM group_team_assignments a JOIN groups_competition g ON g.id=a.group_id JOIN teams t ON t.id=a.team_id WHERE a.group_id=? AND a.status="active" AND a.deleted_at IS NULL');$s->execute([$gid]);$stage=0;$rows=[];foreach($s as $t){$stage=(int)$t['stage_id'];$rows[(int)$t['team_id']]=['team_id'=>(int)$t['team_id'],'team_name'=>$t['name'],'stage_id'=>$stage,'played'=>0,'wins'=>0,'draws'=>0,'losses'=>0,'goals_for'=>0,'goals_against'=>0,'points'=>0,'cards'=>0,'tiebreak_reason'=>''];}if(!$rows)return[];$rules=(new RuleConfigurationService($this->db))->active($tid);$points=$rules['points']??[];$m=$this->db->prepare('SELECT * FROM matches WHERE tournament_id=? AND group_id=? AND status IN ("homologated","walkover") AND deleted_at IS NULL');$m->execute([$tid,$gid]);$matches=$m->fetchAll();foreach($matches as $x)$this->addMatch($rows,$x,$points);$c=$this->db->prepare('SELECT team_id,COUNT(*) cards FROM discipline_ledger WHERE tournament_id=? AND status="active" AND deleted_at IS NULL GROUP BY team_id');$c->execute([$tid]);foreach($c as $x)if(isset($rows[$x['team_id']]))$rows[$x['team_id']]['cards']=(int)$x['cards'];$p=$this->db->prepare('SELECT team_id,SUM(points_delta) d FROM team_penalties WHERE tournament_id=? AND status="active" AND deleted_at IS NULL GROUP BY team_id');$p->execute([$tid]);foreach($p as $x)if(isset($rows[$x['team_id']]))$rows[$x['team_id']]['points']+=(int)$x['d'];$criteria=$rules['tiebreakers']??$rules['standings_tiebreakers']??['points','wins','goal_difference','goals_for'];$rows=array_values($rows);usort($rows,function($a,$b)use($criteria,$matches,$points,$rules){foreach($criteria as $criterion){[$x,$y]=$this->value($criterion,$a,$b,$matches,$points,$rules);if($x!==$y){$a['tiebreak_reason']=$criterion;return$y<=>$x;}}return$a['team_id']<=>$b['team_id'];});return$rows;}
 private function addMatch(array &$rows,array $m,array $points):void{foreach([[(int)$m['home_team_id'],(int)$m['home_score'],(int)$m['away_score']],[(int)$m['away_team_id'],(int)$m['away_score'],(int)$m['home_score']]] as [$id,$gf,$ga]){if(!isset($rows[$id]))continue;$r=&$rows[$id];$r['played']++;$r['goals_for']+=$gf;$r['goals_against']+=$ga;if($gf>$ga){$r['wins']++;$r['points']+=(int)($points['win']??3);}elseif($gf===$ga){$r['draws']++;$r['points']+=(int)($points['draw']??1);}else{$r['losses']++;$r['points']+=(int)($points['loss']??0);}}}
 private function value(string $c,array $a,array $b,array $matches,array $points,array $rules):array{if($c==='goal_difference')return[$a['goals_for']-$a['goals_against'],$b['goals_for']-$b['goals_against']];if(in_array($c,['fewest_cards','fewest_yellow_cards','fewest_red_cards'],true))return[-$a['cards'],-$b['cards']];if($c==='head_to_head'){ $mini=[(int)$a['team_id']=>['p'=>0,'gf'=>0,'ga'=>0],(int)$b['team_id']=>['p'=>0,'gf'=>0,'ga'=>0]];foreach($matches as $m)if(isset($mini[$m['home_team_id']],$mini[$m['away_team_id']]))foreach([[$m['home_team_id'],$m['home_score'],$m['away_score']],[$m['away_team_id'],$m['away_score'],$m['home_score']]]as[$id,$gf,$ga]){$mini[$id]['gf']+=$gf;$mini[$id]['ga']+=$ga;$mini[$id]['p']+=$gf>$ga?(int)($points['win']??3):($gf===$ga?(int)($points['draw']??1):(int)($points['loss']??0));}return[$mini[$a['team_id']]['p']*10000+$mini[$a['team_id']]['gf']-$mini[$a['team_id']]['ga'],$mini[$b['team_id']]['p']*10000+$mini[$b['team_id']]['gf']-$mini[$b['team_id']]['ga']];}if($c==='draw'||$c==='administrative_decision')return[0,0];return[(int)($a[$c]??0),(int)($b[$c]??0)];}
 private function groups(int $tid):array{$s=$this->db->prepare('SELECT g.id FROM groups_competition g JOIN stages st ON st.id=g.stage_id WHERE st.tournament_id=? AND g.deleted_at IS NULL');$s->execute([$tid]);return$s->fetchAll();}
}
