<?php $navigation=['organizations'=>'Organizações','projects'=>'Projetos','tournaments'=>'Campeonatos','teams'=>'Equipes','people'=>'Pessoas','registrations'=>'Inscrições','matches'=>'Partidas','match_reports'=>'Súmulas','news_posts'=>'Notícias','documents'=>'Documentos']; ?>
<div class="admin-layout">
  <aside class="sidebar"><div class="brand-mark">TG</div><strong>Gestão de Torneios</strong><nav><a href="/admin">Visão geral</a><?php foreach($navigation as $key=>$label): ?><a class="<?=$entity===$key?'active':''?>" href="/admin/<?=$key?>"><?=View::e($label)?></a><?php endforeach; ?></nav><a class="logout" href="/logout">Sair</a></aside>
  <main class="content">
    <header class="topbar"><div><span class="eyebrow">Cadastro</span><h1><?=View::e($title)?></h1></div><button class="icon-button" data-theme-toggle aria-label="Alternar tema">◐</button></header>
    <section class="panel"><form method="post" action="/admin/<?=$entity?>/save"><input type="hidden" name="_csrf" value="<?=View::e(Security::csrfToken())?>"><input type="hidden" name="id" value="<?=View::e($editing['id']??'')?>"><div class="form-grid"><?php foreach($meta['fields'] as $field): ?><label><?=View::e(ucwords(str_replace('_',' ',$field)))?><input name="<?=View::e($field)?>" value="<?=View::e($editing[$field]??'')?>"></label><?php endforeach; ?></div><button class="button primary" type="submit"><?=isset($editing)?'Atualizar':'Adicionar'?> registro</button><?php if(isset($editing)): ?><a class="button" href="/admin/<?=$entity?>">Cancelar</a><?php endif; ?></form></section>
    <section class="panel"><div class="panel-head"><h2>Registros</h2><form method="get" action="/admin/<?=$entity?>"><input name="q" value="<?=View::e($query??'')?>" placeholder="Buscar"><button class="button" type="submit">Buscar</button></form><span class="muted"><?=$pager['total']??count($rows)?> encontrados</span></div><?php if($entity==='documents'): ?><a class="button" href="/admin/documents/upload">Enviar documento</a><?php endif; ?><?php if(!$rows): ?><div class="empty">Nenhum registro cadastrado.</div><?php else: ?><div class="table-wrap"><table><thead><tr><?php foreach(array_keys($rows[0]) as $column): if($column==='deleted_at') continue; ?><th><?=View::e(ucwords(str_replace('_',' ',$column)))?></th><?php endforeach; ?><th>Ações</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><?php foreach($row as $column=>$value): if($column==='deleted_at') continue; ?><td><?=View::e((string)$value)?></td><?php endforeach; ?><td><?php if($entity==='documents'): ?><a class="link" href="/admin/documents/<?=$row['id']?>/download">Baixar</a><?php endif; ?><a class="link" href="/admin/<?=$entity?>/<?=$row['id']?>">Editar</a><form method="post" action="/admin/<?=$entity?>/delete" data-confirm="Remover este registro?"><input type="hidden" name="_csrf" value="<?=View::e(Security::csrfToken())?>"><input type="hidden" name="id" value="<?=$row['id']?>"><button class="link danger" type="submit">Remover</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php if(($pager['pages']??1)>1): ?><nav class="pagination"><?php for($p=1;$p<=$pager['pages'];$p++): ?><a class="button" href="/admin/<?=$entity?>?page=<?=$p?>&q=<?=urlencode($query??'')?>"><?=$p?></a><?php endfor; ?></nav><?php endif; ?><?php endif; ?></section>
  </main>
</div>
