<?php use App\Support\Env;use App\Support\View;$base=rtrim((string)Env::get('APP_BASE_PATH',''),'/');$currentPath=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:''; ?>
<div class="admin-layout">
  <button class="drawer-overlay" type="button" data-drawer-close="#admin-navigation" aria-label="Fechar navegacao"></button>
  <aside id="admin-navigation" class="sidebar" data-drawer>
    <div class="brand-mark">TG</div><strong>Gestao de Torneios</strong>
    <?php if(!empty($tournament)): ?><div class="sidebar-context"><strong><?=View::e($tournament['name'])?></strong><small><?=View::e($tournament['category_name']?:'Sem categoria')?> · <?=View::e($tournament['season']?:'Temporada atual')?></small><small><?=View::e($tournament['status'])?></small></div><?php endif; ?>
    <nav aria-label="Navegacao administrativa"><?php foreach($navigation as $item): $href=$base.$item['href']; ?><a class="<?=str_contains($currentPath,$item['href'])?'active':''?>" href="<?=View::e($href)?>"><?=View::e($item['label'])?></a><?php endforeach; ?></nav>
    <a class="logout" href="<?=View::e($base.'/logout')?>">Sair</a>
  </aside>
  <main id="conteudo" class="content dashboard-page">
    <header class="topbar"><button class="button ghost admin-nav-toggle" type="button" data-drawer-toggle="#admin-navigation" aria-controls="admin-navigation" aria-expanded="false">Menu</button><div><nav class="breadcrumbs" aria-label="Caminho"><?php foreach($breadcrumbs as $index=>$crumb): ?><?php if($crumb['href']): ?><a href="<?=View::e($base.$crumb['href'])?>"><?=View::e($crumb['label'])?></a><?php else: ?><span aria-current="page"><?=View::e($crumb['label'])?></span><?php endif; ?><?php if($index<count($breadcrumbs)-1): ?><span aria-hidden="true">/</span><?php endif; ?><?php endforeach; ?></nav><span class="eyebrow"><?=!empty($tournament)?'Campeonato ativo':'Administracao'?></span><h1><?=View::e($module['title'])?></h1><p class="muted"><?=View::e($module['description'])?></p></div><button class="icon-button" data-theme-toggle aria-label="Alternar tema" aria-pressed="false">Tema</button></header>
    <?php if(!empty($tournament)): ?><section class="panel"><div class="panel-head"><div><strong><?=View::e($tournament['name'])?></strong><p class="muted"><?=View::e($tournament['project_name'])?> · <?=View::e($tournament['category_name']?:'Categoria nao definida')?> · <?=View::e($tournament['season']?:'Temporada atual')?></p></div><span class="status"><?=View::e($tournament['status'])?></span></div></section><?php endif; ?>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Modulo em migracao</span><h2><?=View::e($module['title'])?></h2></div><button class="button" type="button" disabled aria-disabled="true"><?=View::e($module['action'])?></button></div><p class="muted">Esta pagina substitui a navegacao pela tela operacional unica. Formularios completos serao migrados na etapa responsavel por este modulo.</p><?php if($records): ?><div class="table-wrap"><table><thead><tr><?php foreach(array_keys($records[0]) as $column): ?><th><?=View::e(ucwords(str_replace('_',' ',$column)))?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($records as $record): ?><tr><?php foreach($record as $value): ?><td><?=View::e((string)$value)?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty">Nenhum dado disponivel neste modulo para o seu escopo.</div><?php endif; ?></section>
  </main>
</div>
