<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Policies\AuthPolicy;use App\Services\TournamentOperationService;use App\Support\Database;use App\Support\Security;use App\Support\Session;use App\Support\View;
final class TournamentOperationController {
 private function db():\PDO{return Database::connection();} private function service():TournamentOperationService{return new TournamentOperationService($this->db());}
 private function tournament(int $id):array{$s=$this->db()->prepare('SELECT * FROM tournaments WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);return$s->fetch()?:throw new \RuntimeException('Campeonato nao encontrado.');}
 private function matchAccess(int $tid,int $match,string $permission):array{$s=$this->db()->prepare('SELECT id FROM matches WHERE id=? AND tournament_id=? AND deleted_at IS NULL');$s->execute([$match,$tid]);if(!$s->fetchColumn()){http_response_code(404);exit('Partida nao encontrada.');}return AuthPolicy::requirePermission($permission,'matches',$match);}
 private function relation(int $tid,string $kind,int $id):void{$sql=['registration'=>'SELECT r.id FROM registrations r WHERE r.id=? AND r.tournament_id=? AND r.deleted_at IS NULL','group'=>'SELECT g.id FROM groups_competition g JOIN stages s ON s.id=g.stage_id WHERE g.id=? AND s.tournament_id=? AND g.deleted_at IS NULL','stage'=>'SELECT id FROM stages WHERE id=? AND tournament_id=? AND deleted_at IS NULL'];$s=$this->db()->prepare($sql[$kind]);$s->execute([$id,$tid]);if(!$s->fetchColumn()){http_response_code(404);exit('Recurso nao encontrado.');}}
 public function dashboard(array $p):string{$id=(int)$p['id'];$u=AuthPolicy::requireTournamentPermission('view',$id);$t=$this->tournament($id);$db=$this->db();$query=function(string $sql,array $args=[])use($db){$s=$db->prepare($sql);$s->execute($args);return$s->fetchAll();};$teams=$query('SELECT t.* FROM teams t JOIN team_tournament_entries e ON e.team_id=t.id WHERE e.tournament_id=? AND e.deleted_at IS NULL ORDER BY t.name',[$id]);$athletes=$query('SELECT p.* FROM people p JOIN team_memberships tm ON tm.person_id=p.id JOIN team_tournament_entries e ON e.team_id=tm.team_id WHERE e.tournament_id=? AND p.person_type="athlete" AND p.deleted_at IS NULL AND tm.deleted_at IS NULL GROUP BY p.id ORDER BY p.full_name',[$id]);$stages=$query('SELECT * FROM stages WHERE tournament_id=? AND deleted_at IS NULL ORDER BY stage_order',[$id]);$groups=$query('SELECT g.*,s.name stage_name,(SELECT COUNT(*) FROM group_team_assignments a WHERE a.group_id=g.id AND a.deleted_at IS NULL) members FROM groups_competition g JOIN stages s ON s.id=g.stage_id WHERE s.tournament_id=? AND g.deleted_at IS NULL ORDER BY g.group_order',[$id]);$registrations=$query('SELECT r.*,p.full_name,t.name team_name FROM registrations r JOIN people p ON p.id=r.person_id JOIN teams t ON t.id=r.team_id WHERE r.tournament_id=? AND r.deleted_at IS NULL ORDER BY r.id DESC',[$id]);$matches=$query('SELECT m.*,h.name home_name,a.name away_name,s.name stage_name FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id LEFT JOIN stages s ON s.id=m.stage_id WHERE m.tournament_id=? AND m.deleted_at IS NULL ORDER BY m.scheduled_at,m.id',[$id]);return View::render('admin/tournament-operations',['title'=>'Operacao do campeonato','user'=>$u,'tournament'=>$t,'teams'=>$teams,'athletes'=>$athletes,'stages'=>$stages,'groups'=>$groups,'registrations'=>$registrations,'matches'=>$matches]);}
 public function register(array $p):never{$tid=(int)$p['id'];$u=AuthPolicy::requireTournamentPermission('manage_roster',$tid);Security::verifyCsrf($_POST['_csrf']??null);try{$this->service()->registerAthlete($tid,(int)$_POST['team_id'],(int)$_POST['person_id'],$_POST['shirt_number']??null);Session::flash('success','Inscricao criada.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function review(array $p):never{$tid=(int)$p['id'];$status=(string)($_POST['status']??'');$u=AuthPolicy::requireTournamentPermission($status==='approved'?'approve_registration':'reject_registration',$tid);Security::verifyCsrf($_POST['_csrf']??null);$this->relation($tid,'registration',(int)$_POST['registration_id']);try{$this->service()->setRegistrationStatus((int)$_POST['registration_id'],$status,(int)$u['id'],$_POST['reason']??null);Session::flash('success','Inscricao atualizada.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function group(array $p):never{$tid=(int)$p['id'];AuthPolicy::requireTournamentPermission('manage_bracket',$tid);Security::verifyCsrf($_POST['_csrf']??null);$this->relation($tid,'stage',(int)$_POST['stage_id']);try{$this->service()->createGroup((int)$_POST['stage_id'],trim((string)$_POST['name']),trim((string)$_POST['code']),(int)$_POST['max_teams']);Session::flash('success','Grupo criado.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function assign(array $p):never{$tid=(int)$p['id'];AuthPolicy::requireTournamentPermission('manage_bracket',$tid);Security::verifyCsrf($_POST['_csrf']??null);$this->relation($tid,'group',(int)$_POST['group_id']);try{$this->service()->assignTeam((int)$_POST['group_id'],(int)$_POST['team_id']);Session::flash('success','Equipe distribuida.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function schedule(array $p):never{$tid=(int)$p['id'];AuthPolicy::requireTournamentPermission('manage_bracket',$tid);Security::verifyCsrf($_POST['_csrf']??null);$this->relation($tid,'group',(int)$_POST['group_id']);try{$n=count($this->service()->generateGroupMatches((int)$_POST['group_id'],$_POST['start_at']?:null));Session::flash('success',$n.' partidas geradas.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function lineup(array $p):never{$tid=(int)$p['id'];$this->matchAccess($tid,(int)$_POST['match_id'],'manage_lineup');Security::verifyCsrf($_POST['_csrf']??null);try{$players=[];foreach($_POST['players']??[] as $person=>$row)if(!empty($row['selected']))$players[]=['person_id'=>(int)$person,'role'=>($row['role']??'substitute'),'shirt_number'=>$row['number']??'','captain'=>!empty($row['captain']),'goalkeeper'=>!empty($row['goalkeeper'])];$this->service()->saveLineup((int)$_POST['match_id'],(int)$_POST['team_id'],$players);Session::flash('success','Escalacao salva.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function event(array $p):never{$tid=(int)$p['id'];$u=$this->matchAccess($tid,(int)$_POST['match_id'],'operate_match');Security::verifyCsrf($_POST['_csrf']??null);try{$this->service()->event((int)$_POST['match_id'],['team_id'=>(int)$_POST['team_id'],'person_id'=>(int)($_POST['person_id']??0)?:null,'assist_person_id'=>(int)($_POST['assist_person_id']??0)?:null,'event_type'=>(string)$_POST['event_type'],'minute'=>(int)($_POST['minute']??0)?:null,'period'=>$_POST['period']??'first'],(int)$u['id']);Session::flash('success','Evento registrado.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function finish(array $p):never{$tid=(int)$p['id'];$this->matchAccess($tid,(int)$_POST['match_id'],'finish_match');Security::verifyCsrf($_POST['_csrf']??null);try{$this->service()->finish((int)$_POST['match_id']);Session::flash('success','Partida pronta para homologacao.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function homologate(array $p):never{$tid=(int)$p['id'];$u=$this->matchAccess($tid,(int)$_POST['match_id'],'homologate_match');Security::verifyCsrf($_POST['_csrf']??null);try{$this->service()->homologate((int)$_POST['match_id'],(int)$u['id']);Session::flash('success','Resultado homologado.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function rectify(array $p):never{$tid=(int)$p['id'];$u=$this->matchAccess($tid,(int)$_POST['match_id'],'approve_rectification');Security::verifyCsrf($_POST['_csrf']??null);try{$this->service()->rectify((int)$_POST['match_id'],trim((string)$_POST['reason']),(int)$u['id']);Session::flash('success','Retificacao iniciada.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function knockout(array $p):never{$tid=(int)$p['id'];AuthPolicy::requireTournamentPermission('manage_bracket',$tid);Security::verifyCsrf($_POST['_csrf']??null);try{$n=count($this->service()->generateKnockout($tid));Session::flash('success',$n.' partidas eliminatorias geradas.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$tid.'/operation');}
 public function pdf(array $p):never{$tid=(int)$p['id'];$this->matchAccess($tid,(int)$p['match'],'download_private_file');$s=$this->db()->prepare('SELECT report_pdf_path FROM matches WHERE id=? AND tournament_id=?');$s->execute([(int)$p['match'],$tid]);$path=$s->fetchColumn();$file=$path?dirname(__DIR__,2).'/storage/'.$path:null;if(!$file||!is_file($file)){http_response_code(404);exit('Sumula indisponivel.');}header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="sumula-'.$p['match'].'.pdf"');readfile($file);exit;}
}
